### ISSUE TITLE
Rails Devise Error “No route matches [GET] ”/users/sign_out“”

### ISSUE THREAD

**Issue by johnfelipe** [ourcities/meurio_accounts#1]
Modify devise.rb to

config.sign_out_via = :get
And change the link

<%= link_to "log out", destroy_user_session_path, method: :get %>

**Comment by iLucker93** [comment]
method: :delete

**Comment by leticia** [comment]
Since this isn't valid anymore, I'm closing this issue. If it's persistent, re-open the issue, please.
